
name: TEST Release

on:
    push:
      tags:
        - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: ubuntu:jammy

    strategy:
      matrix:
        include:
          - NAME: name1
            VERSION: 1.0.0
          - NAME: name2
            VERSION: 1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Build and compress database
        if: github.event.release.tag_name == "v${{ matrix.VERSION }}"
        run: |
          apt-get update
          apt-get -y install tar ca-certificates pigz
          mkdir ${{ matrix.NAME }}
          echo 'yo ${{ matrix.NAME }}' > ${{ matrix.NAME }}/test.txt
          dd if=/dev/urandom of=${{ matrix.NAME }}/randomfile bs=1M count=2560
          tar -cf - ${{ matrix.NAME }} | pigz -0 > ${{ matrix.NAME }}.tar.gz
          npm install axios yargs fs mime-types form-data axios-retry
          ls -lh
          node uploadToZenodo.js --recordName "v${{ matrix.VERSION }}-${{ matrix.NAME }}" --recordDescription 'Release notes for ${{ matrix.VERSION }}-${{ matrix.NAME }}' --recordCreator "Nexomis" --fileToUpload ./${{ matrix.NAME }}.tar.gz --accessToken "${{ secrets.ZENODO_TOKEN }}" > url.txt
      
      # // need read and write permission for workflow https://github.com/{{owner}}/{{repo}}/settings/actions
      - name: Create release 
        uses: actions/github-script@v7
        id: create_release
        with:
          script: |
            const fs = require('fs');
            const urlContent = fs.readFileSync('url.txt', 'utf8');
            let response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v${{ matrix.VERSION }}-${{ matrix.NAME }}',
              name: 'Release ${{ matrix.NAME }} ${{ matrix.VERSION }}',
              body: `Release notes for ${{ matrix.VERSION }}-${{ matrix.NAME }}\n\nzenodo url: ${urlContent}`
            });

